# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Csv2md < Formula
  desc "Convert CSV files to Markdown tables"
  homepage "https://github.com/adrianhredhe/csv2md"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AdrianHRedhe/csv2md/releases/download/v0.1.1/csv2md_0.1.1_darwin_amd64.tar.gz"
      sha256 "7db81b6ad3b327b47361187ec9965cd6d155c4df4eae4b7fac062a41c370519a"

      def install
        bin.install "csv2md"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AdrianHRedhe/csv2md/releases/download/v0.1.1/csv2md_0.1.1_darwin_arm64.tar.gz"
      sha256 "0f92f435bf32131293e617881a28e3ae78eaa4517b658bdb6908d8fe2ff2ec54"

      def install
        bin.install "csv2md"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AdrianHRedhe/csv2md/releases/download/v0.1.1/csv2md_0.1.1_linux_amd64.tar.gz"
      sha256 "e0d1b0b8581a91bf922ee91880c1d1aa2f1f5e3e4edb1fe87a3ef83e2de752a0"
      def install
        bin.install "csv2md"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AdrianHRedhe/csv2md/releases/download/v0.1.1/csv2md_0.1.1_linux_arm64.tar.gz"
      sha256 "5837601782ca5d828a1f651e9a33c4df05d9c2cdfa693fb340a58af20ed8c7f0"
      def install
        bin.install "csv2md"
      end
    end
  end

  test do
    system "#{bin}/csv2md", "-h"
  end
end
